library(usethis)
#complete import
usethis::use_package("quantmod")
usethis::use_package("kableExtra")
usethis::use_package("tidyquant")


#partial import
usethis::use_import_from("stats", "na.omit")
usethis::use_import_from("stats", "lm")
usethis::use_import_from("utils" , "download.file")
usethis::use_import_from("utils", "unzip")
usethis::use_import_from("stats", "summary.lm")
usethis::use_import_from("kableExtra", "kbl" )
usethis::use_import_from("dplyr", "%>%")
usethis::use_import_from("readr","read_csv")
usethis::use_import_from("kableExtra", "pack_rows")
usethis::use_import_from("purrr", "map")
usethis::use_import_from("purrr", "reduce")
usethis::use_import_from("xts" ,"to.period")
usethis::use_import_from("dygraphs", "dyRangeSelector")
usethis::use_import_from("dygraphs", "dyLegend")
usethis::use_import_from("dygraphs", "dySeries")
usethis::use_import_from("dygraphs", "dyOptions")
usethis::use_import_from("dygraphs", "dygraph")
usethis::use_import_from("corrplot", "cor.mtest")
usethis::use_import_from("corrplot", "corrplot")
usethis::use_import_from("corrplot", "COL1")
usethis::use_import_from("knitr", "kable")
usethis::use_import_from("sjPlot" , "tab_df")
usethis::use_import_from("plotly", "plot_ly")
usethis::use_import_from("zoo", "index")
usethis::use_import_from("zoo", "coredata")
usethis::use_import_from("PerformanceAnalytics", "VaR")
usethis::use_import_from("utils", "read.csv")
usethis::use_import_from("zoo", "rollapply")
usethis::use_import_from("dygraphs", "dyCrosshair")
usethis::use_import_from("dygraphs", "dyHighlight")
usethis::use_import_from("xts", "merge.xts")
usethis::use_import_from("PerformanceAnalytics", "Return.portfolio")
usethis::use_import_from("PerformanceAnalytics", "CoVariance")
usethis::use_import_from("stats", "var")
usethis::use_import_from("stats", "cov")
usethis::use_import_from("stats", "sd")
usethis::use_import_from("stats","cor")
usethis::use_import_from("TTR","aroon")
usethis::use_import_from("dygraphs","dyRoller")
usethis::use_import_from("utils","View")
usethis::use_import_from("PerformanceAnalytics","CAPM.CML")
usethis::use_import_from("PerformanceAnalytics","CAPM.RiskPremium")
usethis::use_import_from("PerformanceAnalytics","CAPM.CML.slope")
